FROM node:18-alpine

WORKDIR /app

# Instalar dependencias
COPY package*.json ./
RUN npm install

# Copiar código fuente
COPY . .

# Exponer puertos
EXPOSE 5173 3000

# Comando por defecto (sirve en 3000 por defecto)
CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0", "--port", "3000"]
