version = 0.1

[default.deploy.parameters]
stack_name = "registro-participantes-dev"
resolve_s3 = true
s3_prefix = "registro-participantes-dev"
confirm_changeset = true
capabilities = "CAPABILITY_IAM CAPABILITY_NAMED_IAM"
disable_rollback = true
parameter_overrides = "Stage=\"dev\" DBMasterUsername=\"postgres\" DBMasterPassword=\"Cucuta.2025$\""
image_repositories = []

[default.global.parameters]
region = "us-east-1"
