worker_processes auto;

events {
    worker_connections 1024;
}

http {
    resolver 127.0.0.11 ipv6=off;
    upstream backend_upstream {
        least_conn;
        zone backend_upstream 64k;
        server backend:8000 resolve;
    }

    server {
        listen 80;
        location / {
            proxy_pass http://backend_upstream;
            proxy_http_version 1.1;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header Connection "";
        }
    }
}
