"""add_password_reset_tokens_table

Revision ID: 47b20385352f
Revises: 
Create Date: 2025-11-03 22:08:27.482358

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '47b20385352f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('password_reset_tokens',
    sa.Column('token', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('token')
    )
    op.create_index(op.f('ix_password_reset_tokens_token'), 'password_reset_tokens', ['token'], unique=False)
    op.create_index(op.f('ix_password_reset_tokens_user_id'), 'password_reset_tokens', ['user_id'], unique=False)
    op.drop_index('idx_actividad_fecha', table_name='registros_actividad')
    op.drop_index('idx_actividad_participante', table_name='registros_actividad')
    op.drop_table('registros_actividad')
    op.alter_column('participantes', 'extra_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.drop_index('idx_participantes_email', table_name='participantes')
    op.drop_index('idx_participantes_estado', table_name='participantes')
    op.drop_index('idx_participantes_fecha_registro', table_name='participantes')
    op.drop_constraint('participantes_email_key', 'participantes', type_='unique')
    op.create_index(op.f('ix_participantes_apellido'), 'participantes', ['apellido'], unique=False)
    op.create_index(op.f('ix_participantes_email'), 'participantes', ['email'], unique=True)
    op.create_index(op.f('ix_participantes_estado'), 'participantes', ['estado'], unique=False)
    op.create_index(op.f('ix_participantes_fecha_registro'), 'participantes', ['fecha_registro'], unique=False)
    op.create_index(op.f('ix_participantes_id'), 'participantes', ['id'], unique=False)
    op.create_index(op.f('ix_participantes_nombre'), 'participantes', ['nombre'], unique=False)
    op.alter_column('permissions', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('permissions', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index('idx_permissions_code', table_name='permissions')
    op.drop_constraint('permissions_code_key', 'permissions', type_='unique')
    op.create_index(op.f('ix_permissions_code'), 'permissions', ['code'], unique=True)
    op.drop_index('idx_role_permissions_role', table_name='role_permissions')
    op.create_unique_constraint('uq_role_permissions_role_permission', 'role_permissions', ['role_id', 'permission_id'])
    op.alter_column('roles', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('roles', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index('idx_roles_name', table_name='roles')
    op.drop_constraint('roles_name_key', 'roles', type_='unique')
    op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=True)
    op.drop_index('idx_user_roles_user', table_name='user_roles')
    op.create_unique_constraint('uq_user_roles_user_role', 'user_roles', ['user_id', 'role_id'])
    op.alter_column('users', 'last_login_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_constraint('users_email_key', 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint('users_email_key', 'users', ['email'])
    op.alter_column('users', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('users', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('users', 'last_login_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.drop_constraint('uq_user_roles_user_role', 'user_roles', type_='unique')
    op.create_index('idx_user_roles_user', 'user_roles', ['user_id'], unique=False)
    op.drop_index(op.f('ix_roles_name'), table_name='roles')
    op.create_unique_constraint('roles_name_key', 'roles', ['name'])
    op.create_index('idx_roles_name', 'roles', ['name'], unique=False)
    op.alter_column('roles', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('roles', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_constraint('uq_role_permissions_role_permission', 'role_permissions', type_='unique')
    op.create_index('idx_role_permissions_role', 'role_permissions', ['role_id'], unique=False)
    op.drop_index(op.f('ix_permissions_code'), table_name='permissions')
    op.create_unique_constraint('permissions_code_key', 'permissions', ['code'])
    op.create_index('idx_permissions_code', 'permissions', ['code'], unique=False)
    op.alter_column('permissions', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('permissions', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index(op.f('ix_participantes_nombre'), table_name='participantes')
    op.drop_index(op.f('ix_participantes_id'), table_name='participantes')
    op.drop_index(op.f('ix_participantes_fecha_registro'), table_name='participantes')
    op.drop_index(op.f('ix_participantes_estado'), table_name='participantes')
    op.drop_index(op.f('ix_participantes_email'), table_name='participantes')
    op.drop_index(op.f('ix_participantes_apellido'), table_name='participantes')
    op.create_unique_constraint('participantes_email_key', 'participantes', ['email'])
    op.create_index('idx_participantes_fecha_registro', 'participantes', ['fecha_registro'], unique=False)
    op.create_index('idx_participantes_estado', 'participantes', ['estado'], unique=False)
    op.create_index('idx_participantes_email', 'participantes', ['email'], unique=False)
    op.alter_column('participantes', 'extra_data',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.create_table('registros_actividad',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('participante_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('tipo_evento', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('descripcion', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('fecha', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('usuario', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['participante_id'], ['participantes.id'], name='registros_actividad_participante_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='registros_actividad_pkey')
    )
    op.create_index('idx_actividad_participante', 'registros_actividad', ['participante_id'], unique=False)
    op.create_index('idx_actividad_fecha', 'registros_actividad', ['fecha'], unique=False)
    op.drop_index(op.f('ix_password_reset_tokens_user_id'), table_name='password_reset_tokens')
    op.drop_index(op.f('ix_password_reset_tokens_token'), table_name='password_reset_tokens')
    op.drop_table('password_reset_tokens')
    # ### end Alembic commands ###
